image:
  file: .devcontainer/Dockerfile

tasks:
  - init: |
      nvm use 16
      npm install
    command: npm start

ports:
  - port: 3000
    onOpen: open-preview

# Add any other necessary configurations here
